### ISSUE TITLE
unable to open project

### ISSUE THREAD

**Issue by stephencork** [bnanes/slideset#2]
Hi, 
Thank for making a great plugin for Fiji.  
On opening a fresh updated installation of Fiji with slideset v1.4.4 installed I click on File>Open and the program hangs.  I am running macOS High Sierra v 10.13.6 1.6 i5 processor, 4Gb Memory. This happens most of the time now, sometimes I am able to open a file. This is my first time reporting issues, and happy to assist with any further details you need to troubleshoot.

**Comment by bnanes** [comment]
Thanks for reporting this issue. So far I have not been able to reproduce the problem. Can you provide a little more information? Do you mean File>Open from the Fiji menu or the Slide Set menu? Does the program hang before or after the file selector dialog displays? If the problem is intermittent, have you noticed any specific conditions under which it tends to occur? Does this occur with the first Slide Set project you try to open or subsequent projects during the same application session? If you drag the project file to the Slide Set window, does it open correctly?
The following information, which can be found by selecting Help>About Slide Set from the Slide Set menu, would also be helpful: ImageJ2 version, ImageJ1 version, and Java version.

**Comment by stephencork** [comment]
Great to hear back from you, 

**Conditions for the issue:**
     I am meaning File>open from the slide set menu. This morning I opened Fiji and the Slide Set plug-in and can see the selector window v 1.4.4 with current time and date. I was able to open a project and view the table. Note I find the folder navigation clicking seems to have a delay ie find myself clicking folder multiple times to open). I decided that was the wrong table and went slide set file>open and waited 10 seconds, I clicked the Slide Set menu and it was unresponsive. Then after a minute, the Fiji program became unresponsive. 

**Operating conditions**
Yesterday I was finding that the file open menu did not work on first open the first file most of the time. When I had a project open I was unable to open a second file. I have tried; rebooting-similar, downloading new Fiji and installing Slide Set plugin - still hanging. I recall this issue happening back in January when I was doing the same work and then took a break till now. 
My workaround yesterday was to start a new project and start from scratch. 

**Dragging works**
I am pleased to say that dragging and dropping the project XML file into the slide set window works quickly! 

**here is output from help>about >**
Slide Set version: 1.4.4_
JAR file: /Applications/Fiji%20old.app/plugins/SlideSet/slideset-core-1.4.4_.jar
ImageJ2 version: 2.0.0-rc-69/1.52n
ImageJ1 version: 1.52n

System Information
Operating system: Mac OS X x86_64
Java version: 1.8.0_172
Java location: /Applications/Fiji old.app/java/macosx/jdk1.8.0_172.jre/jre/Contents/Home
Classpath:

/Applications/Fiji old.app/jars/imagej-launcher-4.0.5.jar

**Comment by bnanes** [comment]
I still can't reproduce the problem, but I suspect it may be due to a [concurrency issue](https://docs.oracle.com/javase/tutorial/uiswing/concurrency/index.html). I'm working on a fix which may help. Have you noticed any other situations where the program hangs or becomes unresponsive?

**Comment by stephencork** [comment]
That's ok. The drag and drop project.xml has me working again. I have noticed another hang spot after loading the Table ROI and I select an image via drop down box first. However, using the arrow image selector first then selecting the image from the dropdown box is stable. 
My workflow involves saving a cut version of a photo, thresholding and saving a third binary image for particle analysis. I have added the file name for these two extra images as columns in the project table using sequence insert on table view prior to the file existing. If I select an image filename that has not been created yet, in the ROI Viewer, it does report some console errors and I need to close the ROI window and reopen from the project table to be able to load another image.

**Comment by stephencork** [comment]
Just installed the update to slideset today. **I have been able to use the file/open command and find that ROI files selector seems faster and more stable.** I have another couple days of sizing to do with slideset and will confirm how it goes. 

If you are after any other feedback, I do notice a range of console [Fatal Error]'s displaying when opening the ROI screens. I suspect they may be related to It doesn't stop workflow but can discuss them if you are interested. eg
_ [Fatal Error] :-1:-1: Premature end of file.
[Fatal Error] flake-119.svg:1:150: The value of attribute "xlink:href" associated with an element type "image" must not contain the '<' character.
[Fatal Error] flake-126.svg:1:32: Attribute name "xmln" associated with an element type "svg" must be followed by the ' = ' character.
[Fatal Error] flake-135.svg:1:197: The element type "image" must be terminated by the matching end-tag "</image>".
[Fatal Error] scale-103.svg:1:98: XML document structures must start and end within the same entity.
[Fatal Error] flake-2-148.svg:1:86: The value of attribute "xmlns:xlink" associated with an element type "svg" must not contain the '<' character._
