### ISSUE TITLE
Slideset / Weka Error

### ISSUE THREAD

**Issue by JohnHA106** [bnanes/slideset#4]
Hi there

I'm trying to use Slideset to batch classify 132 images using the Weka trainable segmentation plugin with a classifier made previously in Weka. When I use Slideset to do this after setting up the table and following the instructions on the Slideset website I get an error "“Fatal Error, unable to complete command java.lang.NullPointerExcpetion” in the Slideset terminal.

I've tried using an earlier version of Fiji as advised in one blogpost but still get this error.

Might anyone be able to help?

I've also made a post on the imageJ forum about this: https://forum.image.sc/t/errors-help-needed-with-using-weka-image-segmentation-with-slideset-plugin/89100

Apreciate anyone's help and time.

Thanks!

**Comment by bnanes** [comment]
Hi @JohnHA106 , I can reproduce the error and can confirm this is a bug with the Slide Set wrapper around the Weka segmentation plugin. I will look into a fix.

**Comment by bnanes** [comment]
This issue should now be fixed with [version 1.6.1](https://github.com/bnanes/slideset/releases/tag/1.6.1). You can run the ImageJ updater to download it.

**Comment by JohnHA106** [comment]
Hi @bnanes , thanks so much for resolving this so quickly! I think I have it running now. Appreciate your help
